### ISSUE TITLE
Notes about Prisma connection handling

### ISSUE THREAD

**Issue by RobertCraigie** [shydiscord/shy-dashboard#9]
Hey there!

I'm the creator of Prisma Client Python which I noticed you're using in this project, let me know if you have any questions or suggestions for improvements, I'm more than happy to help!

I couldn't help but notice that you're connecting and disconnecting from the database on each request, this is not the standard usage with Prisma as it works slightly differently to other ORMS, Prisma will create a connection pool and handle connections for you. Connecting and disconnecting to Prisma on each request leads to very inefficient code. For example: https://github.com/shydiscord/shy-dashboard/blob/d33f2b2b36c61f206de570a6963c7b26a0bbae77/shy-dashboard/server/blueprints/api.py#L32-L37

The `async with current_app.prisma: ` line is the offender here. The simplest solution that I know of when using Flask is to simply connect to Prisma before starting the application, e.g. `__main__.py` could be modified like so:

```py
import asyncio
...

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(app.prisma.connect())
    app.run(
        host = "localhost",
        port = 6420
    )
```

And then in your API route handlers you can remove the `with` call:

```py
userData = await User.prisma().find_first(
    where = {
        'user' : userid
    }
)
```

I also know that this *could* be intentional, if that's the case then feel free to disregard what I've said. Let me know if there's anything I can help with!

**Comment by l0gnes** [comment]
Thank you so much for reaching out @RobertCraigie! I'm fairly unfamiliar with Prisma and I ran into an issue where I had the client lingering (More than likely my own fault due to bad control flow) and I wouldn't have even thought to just connect to it when the server starts.

**Comment by l0gnes** [comment]
I do seem to be running into an issue however with your solution where every other request that pulls from the database results in the event loop being closed for some weird reason and I can't seem to figure out where in my code I end up causing the event loop to close.

**Comment by RobertCraigie** [comment]
Can you clarify what you mean by lingering? 

The client should stay connected to the database until the python process closes but if the subprocesses that the client spawns are still running that is a bug :(

If you used the documentation, may I ask how easy it is to read and navigate? I know it's lacking but it's difficult to know how to improve it.

**Comment by RobertCraigie** [comment]
@l0gnes Ah that could be a quirk with the async version of Flask, I'll look into it.

**Comment by l0gnes** [comment]
> If you used the documentation, may I ask how easy it is to read and navigate? I know it's lacking but it's difficult to know how to improve it.

Not having experience with prisma or any sort of ORM with the style I kind of bounced between both your documentation and another for writing the `.prisma` file, admittedly I may have not thoroughly read into how the client had worked, as usually I learn through trail-and-error.

> It should be noted that I hadn't actually tested the solution I proposed.

It seemed like a fairly logical solution compared to my attempt lol.

**Comment by RobertCraigie** [comment]
@l0gnes That issue appears to be due to how flask actually spawns async request handlers, see https://flask.palletsprojects.com/en/2.0.x/async-await/#performance

There are two solutions that come to mind. You can either switch to the synchronous Prisma Client or if you need to use async request handlers you could try out Quart instead which is an async version of Flask.

**Comment by RobertCraigie** [comment]
> I kind of bounced between both your documentation and another for writing the .prisma file

Ah I see, if you're using vscode there is an extension that makes writing the schema file incredibly easy, I should try and make this more prominent in the documentation.

> usually I learn through trial-and-error

Yeah I usually do the same :) I don't think you actually need to read much documentation to use the client as the query arguments wi autocomplete for you if you're using vscode and pylance.

**Comment by l0gnes** [comment]
> Ah I see, if you're using vscode there is an extension that makes writing the schema file incredibly easy, I should try and make this more prominent in the documentation.

I actually did end up using the extension for writing the schema when I did. For databases and ORMs I just prefer being able to look at all the different field types and their explanations since some of them (Such as the DateTime field) often save so much extra hassle.

> Yeah I usually do the same :) I don't think you actually need to read much documentation to use the client as the query arguments wi autocomplete for you if you're using vscode and pylance.

The autocomplete was honestly a great touch, I'm not too well acquainted with ORMs so it was much appreciated!

**Comment by RobertCraigie** [comment]
> The autocomplete was honestly a great touch

I'm glad you enjoyed it :), autocomplete is one of the main reasons I built the ORM in the first place, I don't like using any other ORMs as I find it difficult to write complex queries without autocomplete.

Feel free to ping me or create an issue in https://github.com/RobertCraigie/prisma-client-py if you ever have any questions!

**Comment by l0gnes** [comment]
> Feel free to ping me or create an issue in https://github.com/RobertCraigie/prisma-client-py if you ever have any questions!

Will do! Thanks for all your help!
